### ISSUE TITLE
Fly.io本番環境のDBがリセットできない

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#458]
```
❯ flyctl ssh console -a outdoor-heart-sutra-backend
Connecting to fdaa:1:d5f8:a7b:d86c:83a:df0c:2... complete
root@e784773ced1683:/rails# bin/rails db:reset RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1
PG::ObjectInUse: ERROR:  database "outdoor_heart_sutra_backend" is being accessed by other users
DETAIL:  There is 1 other session using the database.
Couldn't drop database 'outdoor_heart_sutra_backend'
rails aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "outdoor_heart_sutra_backend" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/schema_statements.rb:54:in `drop_database'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/postgresql_database_tasks.rb:32:in `drop'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:224:in `drop'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `block in drop_current'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `drop_current'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
/rails/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

Caused by:
PG::ObjectInUse: ERROR:  database "outdoor_heart_sutra_backend" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/schema_statements.rb:54:in `drop_database'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/postgresql_database_tasks.rb:32:in `drop'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:224:in `drop'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `block in drop_current'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/tasks/database_tasks.rb:239:in `drop_current'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/rails/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
/rails/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
````

**Comment by shirotamaki** [comment]
```
❯ fly status
App
  Name     = outdoor-heart-sutra-backend
  Owner    = personal
  Hostname = outdoor-heart-sutra-backend.fly.dev
  Image    = outdoor-heart-sutra-backend:deployment-01HBSRMCTBVXZ68C2Q4RGVT78C
  Platform = machines

Machines
PROCESS	ID            	VERSION	REGION	STATE  	ROLE	CHECKS	LAST UPDATED
app    	9080e444f06448	43     	nrt   	stopped	    	      	2023-10-03T03:24:55Z
app    	e784773ced1683	43     	nrt   	started	    	      	2023-10-03T03:18:52Z


~/own/outdoor-heart-sutra/backend main
❯ flyctl machine stop e784773ced1683
Sending kill signal to machine e784773ced1683...
e784773ced1683 has been successfully stopped

~/own/outdoor-heart-sutra/backend main
❯ fly status
App
  Name     = outdoor-heart-sutra-backend
  Owner    = personal
  Hostname = outdoor-heart-sutra-backend.fly.dev
  Image    = outdoor-heart-sutra-backend:deployment-01HBSRMCTBVXZ68C2Q4RGVT78C
  Platform = machines

Machines
PROCESS	ID            	VERSION	REGION	STATE  	ROLE	CHECKS	LAST UPDATED
app    	9080e444f06448	43     	nrt   	stopped	    	      	2023-10-03T03:24:55Z
app    	e784773ced1683	43     	nrt   	stopped	    	      	2023-10-03T05:45:56Z
```

**Comment by shirotamaki** [comment]
## psqlを使ってPostgreSQLへの接続

### Postgresデータベースに接続する
> Flyの組織外からPostgresデータベースに接続するには、WireGuard接続が必要です。ただし、ローカルマシンのflyctlを使用すると、ユーザーモードのWireGuardマジックで接続できるため、自分でWireGuardトンネルを設定する必要はありません。psql シェルの場合は、fly postgres connect コマンドを使用するだけです：
https://fly.io/docs/postgres/connecting/connecting-with-flyctl/

#### 接続
`fly postgres connect -a outdoor-heart-sutra-backend-db`

```
❯ fly postgres connect -a outdoor-heart-sutra-backend-db
Connecting to fdaa:1:d5f8:a7b:d829:cbf:915b:2... complete
psql (15.3 (Debian 15.3-1.pgdg120+1))
Type "help" for help.
```

#### データベース一覧の確認
`\list`または`\l`
```
postgres=# \list
                                                         List of databases
            Name             |  Owner   | Encoding |  Collate   |   Ctype    | ICU Locale | Locale Provider |
Access privileges
-----------------------------+----------+----------+------------+------------+------------+-----------------+---
--------------------
 outdoor_heart_sutra_backend | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 postgres                    | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 repmgr                      | repmgr   | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 template0                   | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            | =c
/postgres          +
                             |          |          |            |            |            |                 | po
stgres=CTc/postgres
 template1                   | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            | =c
/postgres          +
                             |          |          |            |            |            |                 | po
stgres=CTc/postgres
(5 rows)
```

#### テーブル一覧の確認
特定のデータベースに接続して、そのデータベース内のテーブルを一覧表示するには、以下のコマンド。
`\c outdoor_heart_sutra_backend`
`\dt`
```
postgres=# \c outdoor_heart_sutra_backend
You are now connected to database "outdoor_heart_sutra_backend" as user "postgres".
outdoor_heart_sutra_backend=# \dt
                               List of relations
 Schema |              Name              | Type  |            Owner
--------+--------------------------------+-------+-----------------------------
 public | active_storage_attachments     | table | outdoor_heart_sutra_backend
 public | active_storage_blobs           | table | outdoor_heart_sutra_backend
 public | active_storage_variant_records | table | outdoor_heart_sutra_backend
 public | ar_internal_metadata           | table | outdoor_heart_sutra_backend
 public | photos                         | table | outdoor_heart_sutra_backend
 public | schema_migrations              | table | outdoor_heart_sutra_backend
 public | sutras                         | table | outdoor_heart_sutra_backend
 public | users                          | table | outdoor_heart_sutra_backend
(8 rows)
```

#### SQLクエリの実行
sqlコマンドが機能するか確認してみる。
```
outdoor_heart_sutra_backend=# Select * from users;
 id | provider |          uid          |         created_at         |         updated_at         |        name
      |             email
----+----------+-----------------------+----------------------------+----------------------------+--------------
------+-------------------------------
  3 | google   | ****** | 2023-08-21 11:52:42.600201 | 2023-08-21 11:52:42.600201 | hogehoge | hogehoge@gmail.com
  4 | google   | ****** | 2023-08-21 11:52:53.241696 | 2023-08-21 11:52:53.241696 | fugafuga | fufgafuga@gmail.com
```

**Comment by shirotamaki** [comment]
# pg_stat_activity で統計情報を取得する

## 動的統計情報ビュー とは
pg_stat_activityは動的統計情報ビューというビルトインのビューの一つ。
https://www.postgresql.jp/document/9.5/html/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW
https://qiita.com/iewori/items/0461f2c0e9e8ce0fd1ee

サーバ当たり１行の形式で、状態や現在の問い合わせ等のプロセスの現在の活動状況に関連した情報を表示する。
取れるデータ達は以下の通り。PostgresSQLのバージョンによって異なるが、よく使いそうなものは変わらなそう。使う場合には要注意。https://ikuty.com/2020/10/14/pg_close_all_sessions/

```
postgres=> \d pg_stat_activity;
           View "pg_catalog.pg_stat_activity"
      Column      |           Type           | Modifiers 
------------------+--------------------------+-----------
 datid            | oid                      |           ; バックエンドが接続するデータベースのOID
 datname          | name                     |           ; バックエンドが接続するデータベースの名前
 pid              | integer                  |           ; バックエンドのプロセスID
 usesysid         | oid                      |           ; バックエンドにログインしたユーザの識別子
 usename          | name                     |           ; バックエンドに接続したユーザの名前
 application_name | text                     |           ; バックエンドに接続したアプリケーションの名前
 client_addr      | inet                     |           ; バックエンドに接続したクライアントのIPアドレス
 client_hostname  | text                     |           ; client_addrの逆引き検索により報告された、接続クライアントのホスト名
 client_port      | integer                  |           ; クライアントがバックエンドとの通信に使用するTCPポート
 backend_start    | timestamp with time zone |           ; プロセスが開始、つまりクライアントがサーバに接続した時刻
 xact_start       | timestamp with time zone |           ; プロセスの現在のトランザクションが開始した時刻
 query_start      | timestamp with time zone |           ; 現在有効な問い合わせが開始した時刻
 state_change     | timestamp with time zone |           ; stateの最終変更時刻
 wait_event_type  | text                     |           ; he type of event for which the backend is waiting
 wait_event       | text                     |           ; Wait event name if backend is currently waiting, otherwise NULL.
 state            | text                     |           ; Current overall state of this backend
 backend_xid      | xid                      |           ; もしあれば、このバックエンドの最上位のトランザクション識別子
 backend_xmin     | xid                      |           ; 現在のバックエンドのxmin
 query            | text                     |           ; バックエンドの最も最近の問い合わせテキスト
 backend_type     | text                     |           ; Type of current backend
```

# 接続中のセッションを切断する
pg_stat_activityの検索結果のPIDをそのままpg_terminate_backend関数に渡して切断する
```
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'outdoor_heart_sutra_backend'
AND pid <> pg_backend_pid();                              //  これは自分自身を切断しないようにという意味
```

**Comment by shirotamaki** [comment]
# デバッグ
## Fly.io のアプリのMachinesの稼働を`0`に設定する

現在、常に1台稼働する設定のため、セッションが切断できないと予想し、一旦設定を`0`にする。

− #454
```
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] 
```

## もう一度、セッションを切断する

```
SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE datname = 'outdoor_heart_sutra_backend'
AND pid <> pg_backend_pid();     
```    

## データベースをリセットする

### 改めて`db:reset`を実行する

**上手くいった！！**

```
❯ flyctl ssh console -a outdoor-heart-sutra-backend
Connecting to fdaa:1:d5f8:a7b:ff:974:9f5b:2... complete
root@9080e6e6b09028:/rails# bin/rails db:reset RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1
Dropped database 'outdoor_heart_sutra_backend'
Created database 'outdoor_heart_sutra_backend'
```
